# @package _global_
defaults:
  - /datamodule: replay_datamodule
  - /litmodule: vqvae
  - override /litmodule/nnmodule: dummy_nnmodule
  - _self_
hydra:
  launcher:
    cpus_per_task: 4
config:
  device: cpu
litmodule:
  config:
    n_hiddens: 240
    sequence_length: 16
    n_res_layers: 4
    downsample:
      - 4
      - 16
      - 16
    embedding_dim: 256
    n_codes: 1024
    resolution: 128
    no_attn: false
  optimizer:
    lr: 0.0003
# datamodule:
# #  per_device_batch_size: 12
# #  num_workers: 4
#   data_path: data/mario_frames_128.h5
#   lazy_load_dir: data/lazy_load
#   split_file: data/basic_split.json
#   subject: sub-01
#   n_frames: ${litmodule.sequence_length}
#   modalities: []
#   time_downsample: 5
#   stride: 5
#   fps: 60
trainer:
  max_epochs: 1
