# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.trainer.trainer.Trainer.html
_target_: lightning.pytorch.trainer.Trainer
strategy: auto
accelerator: ${device}
devices: 1
num_nodes: 1
precision: 32
max_epochs: null
max_steps: 100
val_check_interval: 25
log_every_n_steps: 25
