defaults:
  - local
  - _self_

# https://hydra.cc/docs/plugins/submitit_launcher/
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
account: rrg-pbellec
setup:
  - module load podman/4.5.0
  - nvidia-ctk cdi generate --output=/var/tmp/cdi/nvidia.yaml
  - cp ${SCRATCH}/container.tar ${SLURM_TMPDIR}/${SCRATCH}/.
  - "tar -xf ${SLURM_TMPDIR}/${SCRATCH}/container.tar \
    -C ${SLURM_TMPDIR}/${SCRATCH}/."
