
# ~ CUDA + cuDNN on Ubuntu ~ #
FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

# Prevents `apt install opencv-python` from prompting geographical details
ENV DEBIAN_FRONTEND=noninteractive

# Prevents Python from creating __pycache__ and .pyc files in project folder
ENV PYTHONPYCACHEPREFIX=/.cache/python/

# Install system packages
RUN apt update && apt install -y \
    # OpenMPI
    libopenmpi-dev \
    # UCX for InfiniBand
    libucx0 \
    # Python
    python3-dev \
    python3-pip \
    # OpenCV requires system packages, best to install through apt
    python3-opencv \
    # GitHub packages
    git \
    # Java to install Hydra from source (can be removed once Hydra PR is merged)
    default-jre \
    # Clean up
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
ADD pyproject.toml /cneuroml/pyproject.toml
ADD cneuroml /cneuroml/cneuroml
ADD pyreqs /cneuroml/pyreqs

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -e cneuroml/.[run] \
    && pip uninstall -y cneuroml

RUN apt remove -y \
    python3-pip \
    git \
    default-jre \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/*
