hydra:
  searchpath:
    - file://${oc.env:CNEUROMAX_PATH}/cneuromax/
  run:
    dir: ${data_dir}/hydra/
  sweep:
    dir: ${data_dir}/
    subdir: hydra/

defaults:
  - dl_fitter
  - _self_
  - task: null
