# Make sure to respect 4 space indent & copy the change into `__init__.py`
hydra:
    searchpath:
        - file://${oc.env:CNEUROMAX_PATH}/cneuromax/

defaults:
    - neuroevolution_fitting
    - logger: wandb_simexp
    - _self_
    - base_config
