""":mod:`.kw_pred` project.

Terminology:
- Content ID: A 4-digit number attributed to each piece of content in
the dataset.

Inputs:
- Audio Embeddings (AE) generated by a pre-trained SSL model.
- Audio Short-Time Fourier Transforms (AF).
- Video Embeddings (VE) generated by a pre-trained SSL model.

Outputs:
``.klk`` ``.wav`` predictions (KW). Each piece of content has 4 ``.wav``
files, one for each corner of the chair.

Several assumptions, based on pre-01/2024 decisions, were made in this
module as it would have been too cumbersome/time-consuming to loosen
them:
- The transformed data files are of length 10 seconds.
- The dataset sequence length is 10 seconds.
- The file naming convention for each data modality (ex: AE, AF, VE
having different file naming conventions for milliseconds).
- ``.klk`` ``.wav`` files have a sample rate of 400 Hz.

Several decisions were made in this module to speed up development:
- The second dimension of 3D AE embeddings is averaged to turn them into
2D embeddings.
- All data streams are interpolated to 400 Hz (mode "nearest").

"""

from hydra_zen import ZenStore

from cneuromax.fitting.deeplearning.runner import DeepLearningTaskRunner

from .datamodule import store_configs as store_datamodule_configs
from .litmodule import store_configs as store_litmodule_configs


class TaskRunner(DeepLearningTaskRunner):
    """:mod:`.kw_pred` ``project`` ``task`` runner."""

    @classmethod
    def store_configs(cls: type["TaskRunner"], store: ZenStore) -> None:
        """Stores :mod:`hydra-core` ``project`` configs.

        Args:
            store: See :paramref:`~.BaseTaskRunner.store_configs.store`.
        """
        super().store_configs(store=store)
        store_datamodule_configs(store=store)
        store_litmodule_configs(store=store)
