""":mod:`.kw_pred` project.

Terminology:
- Content ID: A 4-digit number attributed to each piece of content in
the dataset.

Inputs:
- Audio Embeddings (AE) generated by a pre-trained SSL model.
- Audio Short-Time Fourier Transforms (AS).
- Video Embeddings (VE) generated by a pre-trained SSL model.

Outputs:
``.klk`` ``.wav`` predictions (KW). Each piece of content has 4 ``.wav``
files, one for each corner of the chair.
"""

from hydra_zen import ZenStore

from cneuromax.fitting.deeplearning.runner import DeepLearningTaskRunner

from .datamodule import store_configs as store_datamodule_configs
from .litmodule import store_configs as store_litmodule_configs


class TaskRunner(DeepLearningTaskRunner):
    """``project`` ``task`` runner."""

    @classmethod
    def store_configs(cls: type["TaskRunner"], store: ZenStore) -> None:
        """Stores :mod:`hydra-core` ``project`` configs.

        Args:
            store: See :paramref:`~.BaseTaskRunner.store_configs.store`.
        """
        super().store_configs(store=store)
        store_datamodule_configs(store=store)
        store_litmodule_configs(store=store)
