# @package hydra.launcher
defaults:
  - ../base@_here_
  - _self_

setup:
  - module load podman/4.5.0
  - nvidia-ctk cdi generate --output=/var/tmp/cdi/nvidia.yaml
  - cp ${SCRATCH}/container.tar ${SLURM_TMPDIR}/${SCRATCH}/.
  - "tar -xf ${SLURM_TMPDIR}/${SCRATCH}/container.tar \
    -C ${SLURM_TMPDIR}/${SCRATCH}/."
