# @package _global_
defaults:
  - /datamodule: friends_language_encoder
  - /litmodule: friends_language_encoder
  - override /litmodule/nnmodule: friends_language_encoder
  - override hydra/sweeper: orion
  - _self_

model_name: distilbert-base-uncased
layer_name: vocab_transform

hydra:
  launcher:
    gpus_per_node: 1
    cpus_per_task: 4

  sweeper:
    params:
      lr: "loguniform(1e-8, 1.0)"


    experiment:
      name: 'friends_language_encoder'
      version: '1'

    algorithm:
      type: random
      config:
        seed: 1

    worker:
      n_workers: -1
      max_broken: 3
      max_trials: 100

    storage:
      type: legacy
      database:
        type: pickleddb
        host: 'database.pkl'

config:
  device: gpu:0

#Default value
lr: 0.01
