# @package _global_
defaults:
  - /datamodule: friends_language_encoder
  - /litmodule: friends_language_encoder
  - _self_

#     subject: ${subject_data.subject}
#     modalities: [text, bold]
#     bold_dir: null
#     sub_indx: 1
#     model_checkpoint: "gpt2"
#     kernel_size: 1
#     max_epochs: 10
#     devices: 1
#     seed: 42
#     chunk_size: 128
litmodule:
  optimizer:
    lr: 0.002
  nnmodule:
    config:
      dims: [784, 128, 10]
    activation_fn:
      _target_: torch.nn.ReLU
trainer:
  max_epochs: 3
device: gpu

datamodule:
  config:
    tokenizer_name: distilbert-base-uncased
