# @package _global_
defaults:
  - /datamodule: friends_language_encoder
  - /litmodule: friends_language_encoder
  - override /litmodule/nnmodule: friends_language_encoder
  - override /hydra/sweeper: orion
  - _self_

model_name: gpt2
layer_names:
  - ln_f
  - h.11

hydra:
  launcher:
    gpus_per_node: 1
    cpus_per_task: 4

  sweeper:
    params:
      lr: "loguniform(1e-10, 5e-10)"
      wd: "loguniform(1e-3, 5e-2)"


    algorithm:
      type: random
      config:
        seed: 1


    worker:
      max_trials: 10
      max_broken: 15
config:
  device: gpu
  save_every_n_epochs: null


trainer:
  devices:
    - 0
  accumulate_grad_batches: 5

#Default value
lr: 0
wd: 0
