###
# num_cpus_per_task
cpus_per_task: ${num_cpus_per_task}

###
# num_gpus_per_node
gpus_per_node: ${num_gpus_per_node}

###
# num_mem_gb
mem_gb: ${num_mem_gb}

###
# hydra.job.name
name: ${hydra.job.name}

###
# num_nodes
nodes: ${num_nodes}

###
# submitit_folder
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

###
# num_tasks_per_node
tasks_per_node: ${num_tasks_per_node}

###
# num_mins
timeout_min: ${num_mins}
