# @package _global_
defaults:
  - one_klk_wav
  - _self_

device: gpu

litmodule:
  nnmodule:
    config:
      dims: [1,1]
    activation_fn:
      _target_: torch.nn.ReLU

trainer:
  max_epochs: 5000
