defaults:
  - /space: rl_control_nevo
  - /agent: gen_transfer
  - _self_

hydra:
  launcher:
    tasks_per_node: 40
  sweeper:
    params:
      config.mem_transfer: true,false
      config.fit_transfer: true,false
      agent.config.partial_obs: false,true
config:
  agents_per_task: 1
  save_first_gen: true
  save_interval: 10
