# @package _global_
defaults:
  - /space: rl_control_nevo
  - /agent: gen_transfer
  - _self_

hydra:
  launcher:
    tasks_per_node: 40
  sweeper:
    params:
      config.mem_transfer: true,false
      config.fit_transfer: true,false
      agent.config.partial_obs: true,false
      space.config.env_name: Swimmer-v4,Acrobot-v1
config:
  agents_per_task: 1
  save_interval: 10
  save_first_gen: true
