# @package _global_
defaults:
  - /datamodule: kw_pred
  - /datamodule/dataset: kw_pred
  - /litmodule: kw_gen
  - override /litmodule/nnmodule: custom_dit
  - override /hydra/launcher: local
  - _self_

hydra:
  launcher:
    cpus_per_task: 12
    tasks_per_node: 1 #2
    gpus_per_node: 1 #2
  #sweeper:
    #params:
      #datamodule.dataset.config.dataset_percentage: 0.1, 0.5, 0.75, 1.0
      #litmodule.nnmodule.depth: 8,12

config:
  device: gpu
  save_every_n_train_steps: 200
datamodule:
  config:
    val_percentage: 0.01
    #max_per_device_batch_size: 256
    fixed_per_device_batch_size: 256
    fixed_per_device_num_workers: ${hydra:launcher.cpus_per_task}
    shuffle_val_data: False
  dataset:
    config:
      root_data_dir: /data/
      #audio_stft_rel_dir: null
      audio_embeddings_rel_dir: null
      video_embeddings_rel_dir: null
      klk_wavs_rel_dir: KLK_corners_filtered/
trainer:
  max_steps: 10000000
  #max_time: 00:01:00:00
  #max_epochs: 2
  #accumulate_grad_batches: 2
  precision: bf16
  val_check_interval: 200
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0
litmodule:
  optimizer:
    lr: 1e-4
  config:
    log_val_wandb: True
    num_val_wandb_samples: 3
    #predicting: True
  nnmodule:
    klk_seq_len: 4000
    patch_size: 10
    num_klk_corners: 1
    depth: 3 #6
    audio_stft_rel_dir: ${datamodule.dataset.config.audio_stft_rel_dir}
    # yamllint disable-line rule:line-length
    audio_embeddings_rel_dir: ${datamodule.dataset.config.audio_embeddings_rel_dir}
