# @package _global_
defaults:
  - /datamodule: kw_pred
  - /datamodule/dataset: kw_pred
  - /litmodule: kw_gen
  - override /litmodule/nnmodule: custom_dit
  - override /hydra/launcher: local
  - _self_

hydra:
  launcher:
    cpus_per_task: 16
    gpus_per_node: 1
  sweeper:
    params:
      #datamodule.dataset.config.dataset_percentage: 0.5, 1.0
      litmodule.nnmodule.depth: 1,2,3,4,5,6

config:
  device: gpu
  save_every_n_epochs: 0
datamodule:
  config:
    val_percentage: 0.05
    fixed_per_device_batch_size: 256
    fixed_per_device_num_workers: 8
  dataset:
    config:
      root_data_dir: /data/
      #audio_stft_rel_dir: null
      audio_embeddings_rel_dir: null
      video_embeddings_rel_dir: null
      annot_rel_dir: null
      klk_wavs_rel_dir: HEMC_klk_wavs_9hz/
      duration_seconds: 10
      dataset_percentage: 1.0
trainer:
  max_epochs: 4
  precision: bf16
  val_check_interval: 100
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0
  #callbacks:
    #- _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    #  monitor: val/loss
litmodule:
  optimizer:
    lr: 1e-4
  config:
    log_val_wandb: True
  nnmodule:
    klk_seq_len: 4000
    patch_size: 10
    num_klk_corners: 1
    #depth: 1
    audio_stft_rel_dir: ${datamodule.dataset.config.audio_stft_rel_dir}
    # yamllint disable-line rule:line-length
    audio_embeddings_rel_dir: ${datamodule.dataset.config.audio_embeddings_rel_dir}
