""":class:`DeepLearningSubtaskConfig`."""
from dataclasses import dataclass
from typing import Any

from omegaconf import MISSING

from cneuromax.fitting.config import FittingSubtaskConfig


@dataclass
class DeepLearningSubtaskConfig(FittingSubtaskConfig):
    """Structured :mod:`hydra-core` config for Deep Learning fitting.

    Args:
        trainer: Implicit (generated by :mod:`hydra-zen`)\
            ``TrainerHydraConfig`` instance that would have wrapped\
            :class:`~lightning.pytorch.Trainer`.
        litmodule: Implicit (generated by :mod:`hydra-zen`)\
            ``LitModuleHydraConfig`` instance that would have wrapped\
            :class:`~.deeplearning.litmodule.BaseLitModule`.
        datamodule: Implicit (generated by :mod:`hydra-zen`)\
            ``DataModuleHydraConfig`` instance that would have wrapped\
            :class:`~.deeplearning.datamodule.BaseDataModule`.
        logger: Implicit (generated by :mod:`hydra-zen`)\
            ``LoggerHydraConfig`` instance that would have wrapped\
            :class:`~lightning.pytorch.loggers.Logger`.
    """

    trainer: Any = MISSING
    litmodule: Any = MISSING
    datamodule: Any = MISSING
    logger: Any = MISSING
