# @package _global_
# Run the MLP.yaml version first locally, then copy the data over to Béluga
# Example: scp -r MY_DATA_PATH/MNIST/ MY_USER@MY_MACHINE_IP:MY_DATA_PATH/.
defaults:
  - /datamodule: classify_mnist
  - /litmodule: classify_mnist
  - /litmodule/nnmodule: mlp
  - override /hydra/launcher: submitit_slurm
  - _self_
hydra:
  launcher:
    gpus_per_node: 1
    cpus_per_task: 10
    mem_gb: 46
    timeout_min: 15
    account: rrg-pbellec
    python: "/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/\
      apptainer/1.1.8/bin/apptainer \
      exec --nv ${oc.env:SCRATCH}/cneuromax.sif python3"
litmodule:
  nnmodule:
    config:
      dims: [784, 128, 10]
    activation_fn:
      _target_: torch.nn.ReLU
device: gpu
trainer:
  max_epochs: 3
