hydra:
  job:
    chdir: True
  searchpath:
    - file://${oc.env:CNEUROMAX_PATH}/cneuromax/
  run:
    dir: ${run_dir}/
  sweep:
    dir: ${run_dir}/

defaults:
  - hybrid_fitting
  - trainer: base
  - litmodule/scheduler: constant
  - litmodule/optimizer: adamw
  - logger: wandb
  - _self_
  - task: null
