# @package _global_
defaults:
  - /datamodule: mnist
  - /litmodule: gen_mnist
  - override /litmodule/nnmodule: unet
  - _self_
hydra:
  launcher:
    gpus_per_node: 1
    cpus_per_task: 8
config:
  device: gpu
trainer:
  max_epochs: 50
  val_check_interval: 0.25
litmodule:
  optimizer:
    lr: 3e-4
