defaults:
  - base
  - _self_

# https://pytorch.org/docs/stable/generated/torch.optim.Adam.html
_target_: torch.optim.Adam

# Exponential decay rate for the 1st & 2nd moment estimates).
betas: [0.9, 0.999]

# Small constant for numerical stability).
eps: 1e-08
