# Builds the container image with run dependencies & push it to the registry
name: Container Build & Push

on:
  push:
    branches: [main]
    paths:
      - Containerfile
      - pyproject.toml
      - .github/workflows/container-build-push.yaml

jobs:
  container-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the CNeuroMax image
        run: podman build -t cneuromod/cneuromax:latest -f Containerfile .
      - name: Push the CNeuroMax image to Docker Hub
        run: podman push docker.io/cneuromod/cneuromax:latest
      - name: Remove Buildah containers
        run: buildah rm --all
      - name: Remove dangling images
        run: podman image prune -f
