# Builds the container image with run dependencies & push it to the registry
name: Container Build & Push

on:
  push:
    branches: [main]
    paths:
      - Containerfile
      - pyproject.toml
      - .github/workflows/container-build-push.yaml

jobs:
  container-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v3
      - name: Build the container image
        run: podman build -t cneuromod/cneuromax:latest -f Containerfile .
      - name: Login to the registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the container image
        run: >
          podman push cneuromod/cneuromax:latest
          docker://docker.io/cneuromod/cneuromax:latest
