# Builds the Docker image & pushes it to Docker Hub.
name: Docker Build & Push

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - pyproject.toml
      - .github/workflows/docker-build-push.yaml

jobs:
  docker-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the CNeuroMax image
        run: podman build -t cneuromod/cneuromax:latest -f Dockerfile .
      - name: Push the CNeuroMax image to Docker Hub
        run: podman push docker.io/cneuromod/cneuromax:latest
