name: On pull request workflows requiring the CNeuroMax image

on:
  pull_request:
    branches: [main]

jobs:
  on-pr-with-image:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the tentative CNeuroMax image
        run: podman build -t cneuromod/cneuromax:test -f Dockerfile .
      - name: Build the documentation
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          sphinx-build -b html ./docs/ ./docs/build/
      - name: Run mypy
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          mypy --config-file=pyproject.toml cneuromax
      - name: Run pytest
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          pytest --cov cneuromax
      - name: Try Deep Learning on CPU
        run: >
          podman run --privileged --security-opt=label=disable
          --tls-verify=false  --ipc=host --device=nvidia.com/gpu=all
          --net=host --rm -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH} -v /dev/shm:/dev/shm
          -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest python -m
          cneuromax project=classify_mnist task=mlp_cpu
      - name: Try Deep Learning on GPU
        run: >
          podman run --privileged --security-opt=label=disable
          --tls-verify=false  --ipc=host --device=nvidia.com/gpu=all
          --net=host --rm -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH} -v /dev/shm:/dev/shm
          -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest python -m
          cneuromax project=classify_mnist task=mlp
      - name: Try Neuroevolution on CPU
        run: >
          podman run --privileged --security-opt=label=disable
          --tls-verify=false  --ipc=host --device=nvidia.com/gpu=all
          --net=host --rm -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH} -v /dev/shm:/dev/shm
          -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest python -m
          cneuromax project=neuroevorl_control task=acrobot
          config.total_num_gens=10
