name: On pull request workflows requiring the CNeuroMax image

on:
  pull_request:
    branches: [main]

jobs:
  on-pr-with-image:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the tentative CNeuroMax image
        run: podman build -t cneuromod/cneuromax:test -f Dockerfile .
      - name: Build the documentation
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          sphinx-build -b html ./docs/ ./docs/build/
      - name: Run mypy
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          mypy --config-file=pyproject.toml cneuromax
      - name: Run pytest
        run: >
          podman run --rm -v $PWD:/cneuromax -w /cneuromax
          cneuromod/cneuromax:test
          pytest --cov cneuromax
      - name: Create WANDB_KEY.txt file
        run: echo ${{ secrets.WANDB_KEY }} > WANDB_KEY.txt
      - name: Try Deep Learning on CPU
        run: >
          docker run --privileged --rm
          -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -e HYDRA_FULL_ERROR=1 -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH}
          -v /dev/shm:/dev/shm -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest
          python3 -m cneuromax project=classify_mnist task=mlp_cpu
          logger.entity=maximilienlc
      - name: Try Deep Learning on GPU
        run: >
          docker run --privileged --gpus all --rm
          -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -e HYDRA_FULL_ERROR=1 -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH}
          -v /dev/shm:/dev/shm -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest
          python3 -m cneuromax project=classify_mnist task=mlp
          logger.entity=maximilienlc
      - name: Try Neuroevolution on CPU
        run: >
          docker run --privileged --gpus all --rm
          -e CNEUROMAX_PATH=${CNEUROMAX_PATH}
          -e PYTHONPATH=${PYTHONPATH}:${CNEUROMAX_PATH}
          -e HYDRA_FULL_ERROR=1 -v ${CNEUROMAX_PATH}:${CNEUROMAX_PATH}
          -v /dev/shm:/dev/shm -w ${CNEUROMAX_PATH} cneuromod/cneuromax:latest
          python3 -m cneuromax project=neuroevorl_control task=acrobot
          config.total_num_gens=10 logger.entity=maximilienlc
