name: On push workflows requiring the CNeuroMax image

on:
  push:
    branches: [main]

jobs:
  podman-build:
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the tentative CNeuroMax Podman image
        run: podman build -t cneuromod/cneuromax:latest -f Dockerfile .
  podman-push:
    needs: podman-build
    runs-on: self-hosted
    steps:
      - name: Push the tentative CNeuroMax Podman image
        run: podman push docker.io/cneuromod/cneuromax:latest
  sphinx-build:
    needs: podman-build
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Build the documentation with Sphinx
        run: >
          podman run --rm -v ${PWD}:${PWD} -w ${PWD} cneuromod/cneuromax:test
          sphinx-build -b html ./docs/ ./docs/build/
      - name: Deploy the documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/
  mypy:
    needs: podman-build
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Static type checking with Mypy
        run: >
          podman run --rm -v ${PWD}:${PWD} -w ${PWD} cneuromod/cneuromax:test
          mypy --config-file=pyproject.toml cneuromax
  pytest:
    needs: podman-build
    runs-on: self-hosted
    steps:
      - name: Checkout the GitHub repo
        uses: actions/checkout@v4
      - name: Unit testing with pytest
        run: >
          podman run --rm -v ${PWD}:${PWD} -w ${PWD} cneuromod/cneuromax:test
          pytest --cov cneuromax
